(define (plan tot-solution)
  (:problem tot)
  (:steps (travel Jon_Horchler Hip-Hop-Dance-Studio Dawnbreak-Airport)
          (retrieve Jon_Horchler overpriced_food Dawnbreak-Airport)
          (give Jon_Horchler John_Joyce overpriced_food Dawnbreak-Airport)
          (retrieve Richard_Skaar flower Starlight-Park)
          (travel Richard_Skaar Starlight-Park Hip-Hop-Dance-Studio)
          (give Richard_Skaar Rebecca_Oldenburg flower Hip-Hop-Dance-Studio)
          (retrieve Richard_Skaar sick_dance_moves_brochure Hip-Hop-Dance-Studio)
          (vigorousdance Richard_Skaar)
          (flirt Richard_Skaar Rebecca_Oldenburg Hip-Hop-Dance-Studio)))