(define (plan tot-solution)
  (:problem tot)
  (:steps (travel Richard_Skaar Starlight-Park Hip-Hop-Dance-Studio)
          (retrieve Richard_Skaar sick_dance_moves_brochure Hip-Hop-Dance-Studio)
          (vigorousdance Richard_Skaar)
          (give Richard_Skaar Rebecca_Oldenburg sick_dance_moves_brochure Hip-Hop-Dance-Studio)
          (flirt Richard_Skaar Rebecca_Oldenburg Hip-Hop-Dance-Studio)
          (steal Jon_Horchler Rebecca_Oldenburg sick_dance_moves_brochure Hip-Hop-Dance-Studio)
          (travel Jon_Horchler Hip-Hop-Dance-Studio Dawnbreak-Airport)
          (give Jon_Horchler John_Joyce sick_dance_moves_brochure Dawnbreak-Airport)))