(define (plan aladdin-cave-solution)
  (:problem aladdin-cave)
  (:steps (fall-in-love king jasmine castle)
          (order king hero castle (loves jasmine king))
          (go hero castle mountain)
          (slay hero dragon mountain)
          (pillage hero dragon lamp mountain)
          (summon hero genie lamp mountain)
          (command hero genie lamp (loves jasmine king))
          (love-spell genie jasmine king)
          (marry king jasmine castle)
          (appear-threatening genie hero mountain)
          (slay hero genie mountain)))