(define (space aladdin-cave)
  (:literals (alive dragon)
             (not (alive dragon))
             (alive genie)
             (not (alive genie))
             (alive hero)
             (alive jasmine)
             (alive king)
             (at dragon castle)
             (at dragon mountain)
             (at genie castle)
             (not (at genie castle))
             (at genie mountain)
             (not (at genie mountain))
             (at hero castle)
             (not (at hero castle))
             (at hero mountain)
             (not (at hero mountain))
             (at jasmine castle)
             (not (at jasmine castle))
             (at jasmine mountain)
             (not (at jasmine mountain))
             (at king castle)
             (not (at king castle))
             (at king mountain)
             (not (at king mountain))
             (beautiful jasmine)
             (confined genie)
             (controls genie genie)
             (controls hero genie)
             (controls jasmine genie)
             (controls king genie)
             (delegated dragon (alive dragon) genie)
             (delegated dragon (alive genie) genie)
             (delegated dragon (alive hero) genie)
             (delegated dragon (alive jasmine) genie)
             (delegated dragon (alive king) genie)
             (delegated dragon (at dragon castle) genie)
             (delegated dragon (at dragon mountain) genie)
             (delegated dragon (at genie castle) genie)
             (delegated dragon (at genie mountain) genie)
             (delegated dragon (at hero castle) genie)
             (delegated dragon (at hero mountain) genie)
             (delegated dragon (at jasmine castle) genie)
             (delegated dragon (at jasmine mountain) genie)
             (delegated dragon (at king castle) genie)
             (delegated dragon (at king mountain) genie)
             (delegated dragon (controls hero genie) genie)
             (delegated dragon (controls jasmine genie) genie)
             (delegated dragon (controls king genie) genie)
             (delegated dragon (has dragon lamp) genie)
             (delegated dragon (has genie lamp) genie)
             (delegated dragon (has hero lamp) genie)
             (delegated dragon (has jasmine lamp) genie)
             (delegated dragon (has king lamp) genie)
             (delegated dragon (in genie lamp) genie)
             (delegated dragon (loves hero jasmine) genie)
             (delegated dragon (loves jasmine hero) genie)
             (delegated dragon (loves jasmine king) genie)
             (delegated dragon (loves king jasmine) genie)
             (delegated dragon (loyal-to hero king) genie)
             (delegated dragon (married-to hero jasmine) genie)
             (delegated dragon (married-to jasmine hero) genie)
             (delegated dragon (married-to jasmine king) genie)
             (delegated dragon (married-to king jasmine) genie)
             (delegated hero (alive dragon) genie)
             (delegated hero (alive genie) genie)
             (delegated hero (alive hero) genie)
             (delegated hero (alive jasmine) genie)
             (delegated hero (alive king) genie)
             (delegated hero (at dragon castle) genie)
             (delegated hero (at dragon mountain) genie)
             (delegated hero (at genie castle) genie)
             (delegated hero (at genie mountain) genie)
             (delegated hero (at hero castle) genie)
             (delegated hero (at hero mountain) genie)
             (delegated hero (at jasmine castle) genie)
             (delegated hero (at jasmine mountain) genie)
             (delegated hero (at king castle) genie)
             (delegated hero (at king mountain) genie)
             (delegated hero (controls hero genie) genie)
             (delegated hero (controls jasmine genie) genie)
             (delegated hero (controls king genie) genie)
             (delegated hero (has dragon lamp) genie)
             (delegated hero (has genie lamp) genie)
             (delegated hero (has hero lamp) genie)
             (delegated hero (has jasmine lamp) genie)
             (delegated hero (has king lamp) genie)
             (delegated hero (in genie lamp) genie)
             (delegated hero (loves hero jasmine) genie)
             (delegated hero (loves jasmine hero) genie)
             (delegated hero (loves jasmine king) genie)
             (delegated hero (loves king jasmine) genie)
             (delegated hero (loyal-to hero king) genie)
             (delegated hero (married-to hero jasmine) genie)
             (delegated hero (married-to jasmine hero) genie)
             (delegated hero (married-to jasmine king) genie)
             (delegated hero (married-to king jasmine) genie)
             (delegated jasmine (alive dragon) genie)
             (delegated jasmine (alive genie) genie)
             (delegated jasmine (alive hero) genie)
             (delegated jasmine (alive jasmine) genie)
             (delegated jasmine (alive king) genie)
             (delegated jasmine (at dragon castle) genie)
             (delegated jasmine (at dragon mountain) genie)
             (delegated jasmine (at genie castle) genie)
             (delegated jasmine (at genie mountain) genie)
             (delegated jasmine (at hero castle) genie)
             (delegated jasmine (at hero mountain) genie)
             (delegated jasmine (at jasmine castle) genie)
             (delegated jasmine (at jasmine mountain) genie)
             (delegated jasmine (at king castle) genie)
             (delegated jasmine (at king mountain) genie)
             (delegated jasmine (controls hero genie) genie)
             (delegated jasmine (controls jasmine genie) genie)
             (delegated jasmine (controls king genie) genie)
             (delegated jasmine (has dragon lamp) genie)
             (delegated jasmine (has genie lamp) genie)
             (delegated jasmine (has hero lamp) genie)
             (delegated jasmine (has jasmine lamp) genie)
             (delegated jasmine (has king lamp) genie)
             (delegated jasmine (in genie lamp) genie)
             (delegated jasmine (loves hero jasmine) genie)
             (delegated jasmine (loves jasmine hero) genie)
             (delegated jasmine (loves jasmine king) genie)
             (delegated jasmine (loves king jasmine) genie)
             (delegated jasmine (loyal-to hero king) genie)
             (delegated jasmine (married-to hero jasmine) genie)
             (delegated jasmine (married-to jasmine hero) genie)
             (delegated jasmine (married-to jasmine king) genie)
             (delegated jasmine (married-to king jasmine) genie)
             (delegated king (alive dragon) genie)
             (delegated king (alive dragon) hero)
             (delegated king (alive genie) genie)
             (delegated king (alive genie) hero)
             (delegated king (alive hero) genie)
             (delegated king (alive hero) hero)
             (delegated king (alive jasmine) genie)
             (delegated king (alive jasmine) hero)
             (delegated king (alive king) genie)
             (delegated king (alive king) hero)
             (delegated king (at dragon castle) genie)
             (delegated king (at dragon castle) hero)
             (delegated king (at dragon mountain) genie)
             (delegated king (at dragon mountain) hero)
             (delegated king (at genie castle) genie)
             (delegated king (at genie castle) hero)
             (delegated king (at genie mountain) genie)
             (delegated king (at genie mountain) hero)
             (delegated king (at hero castle) genie)
             (delegated king (at hero castle) hero)
             (delegated king (at hero mountain) genie)
             (delegated king (at hero mountain) hero)
             (delegated king (at jasmine castle) genie)
             (delegated king (at jasmine castle) hero)
             (delegated king (at jasmine mountain) genie)
             (delegated king (at jasmine mountain) hero)
             (delegated king (at king castle) genie)
             (delegated king (at king castle) hero)
             (delegated king (at king mountain) genie)
             (delegated king (at king mountain) hero)
             (delegated king (controls hero genie) genie)
             (delegated king (controls hero genie) hero)
             (delegated king (controls jasmine genie) genie)
             (delegated king (controls jasmine genie) hero)
             (delegated king (controls king genie) genie)
             (delegated king (controls king genie) hero)
             (delegated king (has dragon lamp) genie)
             (delegated king (has dragon lamp) hero)
             (delegated king (has genie lamp) genie)
             (delegated king (has genie lamp) hero)
             (delegated king (has hero lamp) genie)
             (delegated king (has hero lamp) hero)
             (delegated king (has jasmine lamp) genie)
             (delegated king (has jasmine lamp) hero)
             (delegated king (has king lamp) genie)
             (delegated king (has king lamp) hero)
             (delegated king (in genie lamp) genie)
             (delegated king (in genie lamp) hero)
             (delegated king (loves hero jasmine) genie)
             (delegated king (loves hero jasmine) hero)
             (delegated king (loves jasmine hero) genie)
             (delegated king (loves jasmine hero) hero)
             (delegated king (loves jasmine king) genie)
             (delegated king (loves jasmine king) hero)
             (delegated king (loves king jasmine) genie)
             (delegated king (loves king jasmine) hero)
             (delegated king (loyal-to hero king) genie)
             (delegated king (loyal-to hero king) hero)
             (delegated king (married-to hero jasmine) genie)
             (delegated king (married-to hero jasmine) hero)
             (delegated king (married-to jasmine hero) genie)
             (delegated king (married-to jasmine hero) hero)
             (delegated king (married-to jasmine king) genie)
             (delegated king (married-to jasmine king) hero)
             (delegated king (married-to king jasmine) genie)
             (delegated king (married-to king jasmine) hero)
             (not (confined genie))
             (has dragon lamp)
             (not (has dragon lamp))
             (has genie lamp)
             (not (has genie lamp))
             (has hero lamp)
             (has jasmine lamp)
             (has king lamp)
             (in genie lamp)
             (intends genie (alive dragon))
             (intends genie (alive genie))
             (intends genie (alive hero))
             (intends genie (alive jasmine))
             (intends genie (alive king))
             (intends genie (at dragon castle))
             (intends genie (at dragon mountain))
             (intends genie (at genie castle))
             (intends genie (at genie mountain))
             (intends genie (at hero castle))
             (intends genie (at hero mountain))
             (intends genie (at jasmine castle))
             (intends genie (at jasmine mountain))
             (intends genie (at king castle))
             (intends genie (at king mountain))
             (intends genie (controls hero genie))
             (intends genie (controls jasmine genie))
             (intends genie (controls king genie))
             (intends genie (has dragon lamp))
             (intends genie (has genie lamp))
             (intends genie (has hero lamp))
             (intends genie (has jasmine lamp))
             (intends genie (has king lamp))
             (intends genie (in genie lamp))
             (intends genie (loves hero jasmine))
             (intends genie (loves jasmine hero))
             (intends genie (loves jasmine king))
             (intends genie (loves king jasmine))
             (intends genie (loyal-to hero king))
             (intends genie (married-to hero jasmine))
             (intends genie (married-to jasmine hero))
             (intends genie (married-to jasmine king))
             (intends genie (married-to king jasmine))
             (intends hero (alive dragon))
             (intends hero (alive genie))
             (intends hero (alive hero))
             (intends hero (alive jasmine))
             (intends hero (alive king))
             (intends hero (at dragon castle))
             (intends hero (at dragon mountain))
             (intends hero (at genie castle))
             (intends hero (at genie mountain))
             (intends hero (at hero castle))
             (intends hero (at hero mountain))
             (intends hero (at jasmine castle))
             (intends hero (at jasmine mountain))
             (intends hero (at king castle))
             (intends hero (at king mountain))
             (intends hero (controls king genie))
             (intends hero (has dragon lamp))
             (intends hero (has genie lamp))
             (intends hero (has king lamp))
             (intends hero (in genie lamp))
             (intends hero (loves jasmine king))
             (intends hero (loves king jasmine))
             (intends hero (loyal-to hero king))
             (intends hero (married-to hero jasmine))
             (intends hero (married-to king jasmine))
             (intends jasmine (married-to jasmine hero))
             (intends jasmine (married-to jasmine king))
             (intends king (married-to king jasmine))
             (not (has hero lamp))
             (not (has jasmine lamp))
             (not (has king lamp))
             (not (in genie lamp))
             (loves hero jasmine)
             (not (loves hero jasmine))
             (loves jasmine hero)
             (not (loves jasmine hero))
             (loves jasmine king)
             (not (loves jasmine king))
             (loves king jasmine)
             (not (loves king jasmine))
             (loyal-to hero king)
             (married hero)
             (married jasmine)
             (married king)
             (married-to hero jasmine)
             (married-to jasmine hero)
             (married-to jasmine king)
             (married-to king jasmine)
             (scary dragon)
             (scary genie)
             (single hero)
             (not (single hero))
             (single jasmine)
             (not (single jasmine))
             (single king)
             (not (single king)))
  (:steps (go hero castle mountain)
          (go hero mountain castle)
          (go king castle mountain)
          (go king mountain castle)
          (go jasmine castle mountain)
          (go jasmine mountain castle)
          (go genie castle mountain)
          (go genie mountain castle)
          (slay hero dragon castle)
          (slay hero dragon mountain)
          (slay hero genie castle)
          (slay hero genie mountain)
          (pillage hero dragon lamp castle)
          (pillage hero dragon lamp mountain)
          (pillage hero genie lamp castle)
          (pillage hero genie lamp mountain)
          (pillage king dragon lamp castle)
          (pillage king dragon lamp mountain)
          (pillage king genie lamp castle)
          (pillage king genie lamp mountain)
          (pillage jasmine dragon lamp castle)
          (pillage jasmine dragon lamp mountain)
          (pillage jasmine genie lamp castle)
          (pillage jasmine genie lamp mountain)
          (pillage genie dragon lamp castle)
          (pillage genie dragon lamp mountain)
          (pillage genie genie lamp castle)
          (pillage genie genie lamp mountain)
          (give hero king lamp castle)
          (give hero king lamp mountain)
          (give hero dragon lamp castle)
          (give hero dragon lamp mountain)
          (give hero genie lamp castle)
          (give hero genie lamp mountain)
          (give king dragon lamp castle)
          (give king dragon lamp mountain)
          (give king genie lamp castle)
          (give king genie lamp mountain)
          (give jasmine dragon lamp castle)
          (give jasmine dragon lamp mountain)
          (give jasmine genie lamp castle)
          (give jasmine genie lamp mountain)
          (give genie hero lamp castle)
          (give genie hero lamp mountain)
          (give genie king lamp castle)
          (give genie king lamp mountain)
          (give genie jasmine lamp castle)
          (give genie jasmine lamp mountain)
          (give genie dragon lamp castle)
          (give genie dragon lamp mountain)
          (summon hero genie lamp castle)
          (summon hero genie lamp mountain)
          (summon king genie lamp castle)
          (summon king genie lamp mountain)
          (summon jasmine genie lamp castle)
          (summon jasmine genie lamp mountain)
          (summon genie genie lamp castle)
          (summon genie genie lamp mountain)
          (love-spell genie hero jasmine)
          (love-spell genie king jasmine)
          (love-spell genie jasmine hero)
          (love-spell genie jasmine king)
          (marry hero jasmine castle)
          (marry hero jasmine mountain)
          (marry king jasmine castle)
          (marry king jasmine mountain)
          (fall-in-love hero jasmine castle)
          (fall-in-love hero jasmine mountain)
          (fall-in-love king jasmine castle)
          (fall-in-love king jasmine mountain)
          (order king hero castle (alive dragon))
          (order king hero castle (alive genie))
          (order king hero castle (alive hero))
          (order king hero castle (alive jasmine))
          (order king hero castle (alive king))
          (order king hero castle (at dragon castle))
          (order king hero castle (at dragon mountain))
          (order king hero castle (at genie castle))
          (order king hero castle (at genie mountain))
          (order king hero castle (at hero castle))
          (order king hero castle (at hero mountain))
          (order king hero castle (at jasmine castle))
          (order king hero castle (at jasmine mountain))
          (order king hero castle (at king castle))
          (order king hero castle (at king mountain))
          (order king hero castle (in genie lamp))
          (order king hero castle (has dragon lamp))
          (order king hero castle (has genie lamp))
          (order king hero castle (has king lamp))
          (order king hero castle (loyal-to hero king))
          (order king hero castle (controls king genie))
          (order king hero castle (loves jasmine king))
          (order king hero castle (loves king jasmine))
          (order king hero castle (married-to king jasmine))
          (order king hero mountain (alive dragon))
          (order king hero mountain (alive genie))
          (order king hero mountain (alive hero))
          (order king hero mountain (alive jasmine))
          (order king hero mountain (alive king))
          (order king hero mountain (at dragon castle))
          (order king hero mountain (at dragon mountain))
          (order king hero mountain (at genie castle))
          (order king hero mountain (at genie mountain))
          (order king hero mountain (at hero castle))
          (order king hero mountain (at hero mountain))
          (order king hero mountain (at jasmine castle))
          (order king hero mountain (at jasmine mountain))
          (order king hero mountain (at king castle))
          (order king hero mountain (at king mountain))
          (order king hero mountain (in genie lamp))
          (order king hero mountain (has dragon lamp))
          (order king hero mountain (has genie lamp))
          (order king hero mountain (has king lamp))
          (order king hero mountain (loyal-to hero king))
          (order king hero mountain (controls king genie))
          (order king hero mountain (loves jasmine king))
          (order king hero mountain (loves king jasmine))
          (order king hero mountain (married-to king jasmine))
          (command hero genie lamp (alive dragon))
          (command hero genie lamp (alive genie))
          (command hero genie lamp (alive hero))
          (command hero genie lamp (alive jasmine))
          (command hero genie lamp (alive king))
          (command hero genie lamp (at dragon castle))
          (command hero genie lamp (at dragon mountain))
          (command hero genie lamp (at genie castle))
          (command hero genie lamp (at genie mountain))
          (command hero genie lamp (at hero castle))
          (command hero genie lamp (at hero mountain))
          (command hero genie lamp (at jasmine castle))
          (command hero genie lamp (at jasmine mountain))
          (command hero genie lamp (at king castle))
          (command hero genie lamp (at king mountain))
          (command hero genie lamp (in genie lamp))
          (command hero genie lamp (has dragon lamp))
          (command hero genie lamp (has genie lamp))
          (command hero genie lamp (has hero lamp))
          (command hero genie lamp (has king lamp))
          (command hero genie lamp (loyal-to hero king))
          (command hero genie lamp (controls hero genie))
          (command hero genie lamp (controls king genie))
          (command hero genie lamp (loves hero jasmine))
          (command hero genie lamp (loves jasmine hero))
          (command hero genie lamp (loves jasmine king))
          (command hero genie lamp (loves king jasmine))
          (command hero genie lamp (married-to hero jasmine))
          (command hero genie lamp (married-to king jasmine))
          (command king genie lamp (alive dragon))
          (command king genie lamp (alive genie))
          (command king genie lamp (alive hero))
          (command king genie lamp (alive jasmine))
          (command king genie lamp (alive king))
          (command king genie lamp (at dragon castle))
          (command king genie lamp (at dragon mountain))
          (command king genie lamp (at genie castle))
          (command king genie lamp (at genie mountain))
          (command king genie lamp (at hero castle))
          (command king genie lamp (at hero mountain))
          (command king genie lamp (at jasmine castle))
          (command king genie lamp (at jasmine mountain))
          (command king genie lamp (at king castle))
          (command king genie lamp (at king mountain))
          (command king genie lamp (in genie lamp))
          (command king genie lamp (has dragon lamp))
          (command king genie lamp (has genie lamp))
          (command king genie lamp (has king lamp))
          (command king genie lamp (loyal-to hero king))
          (command king genie lamp (controls king genie))
          (command king genie lamp (loves jasmine king))
          (command king genie lamp (loves king jasmine))
          (command king genie lamp (married-to king jasmine))
          (command jasmine genie lamp (alive dragon))
          (command jasmine genie lamp (alive genie))
          (command jasmine genie lamp (alive hero))
          (command jasmine genie lamp (alive jasmine))
          (command jasmine genie lamp (alive king))
          (command jasmine genie lamp (at dragon castle))
          (command jasmine genie lamp (at dragon mountain))
          (command jasmine genie lamp (at genie castle))
          (command jasmine genie lamp (at genie mountain))
          (command jasmine genie lamp (at hero castle))
          (command jasmine genie lamp (at hero mountain))
          (command jasmine genie lamp (at jasmine castle))
          (command jasmine genie lamp (at jasmine mountain))
          (command jasmine genie lamp (at king castle))
          (command jasmine genie lamp (at king mountain))
          (command jasmine genie lamp (in genie lamp))
          (command jasmine genie lamp (has dragon lamp))
          (command jasmine genie lamp (has genie lamp))
          (command jasmine genie lamp (has jasmine lamp))
          (command jasmine genie lamp (controls jasmine genie))
          (command jasmine genie lamp (loves hero jasmine))
          (command jasmine genie lamp (loves jasmine hero))
          (command jasmine genie lamp (loves jasmine king))
          (command jasmine genie lamp (loves king jasmine))
          (command jasmine genie lamp (married-to jasmine hero))
          (command jasmine genie lamp (married-to jasmine king))
          (appear-threatening dragon hero castle)
          (appear-threatening dragon hero mountain)
          (appear-threatening dragon king castle)
          (appear-threatening dragon king mountain)
          (appear-threatening dragon jasmine castle)
          (appear-threatening dragon jasmine mountain)
          (appear-threatening dragon genie castle)
          (appear-threatening dragon genie mountain)
          (appear-threatening genie hero castle)
          (appear-threatening genie hero mountain)
          (appear-threatening genie king castle)
          (appear-threatening genie king mountain)
          (appear-threatening genie jasmine castle)
          (appear-threatening genie jasmine mountain)
          (appear-threatening genie dragon castle)
          (appear-threatening genie dragon mountain))
  (:axioms (:axiom
             :context (and (delegated hero (alive dragon) genie)
                           (alive dragon))
             :implies (alive dragon))
           (:axiom
             :context (and (delegated hero (alive genie) genie)
                           (alive genie))
             :implies (alive genie))
           (:axiom
             :context (and (delegated hero (alive hero) genie)
                           (alive hero))
             :implies (alive hero))
           (:axiom
             :context (and (delegated hero (alive jasmine) genie)
                           (alive jasmine))
             :implies (alive jasmine))
           (:axiom
             :context (and (delegated hero (alive king) genie)
                           (alive king))
             :implies (alive king))
           (:axiom
             :context (and (delegated hero (at dragon castle) genie)
                           (at dragon castle))
             :implies (at dragon castle))
           (:axiom
             :context (and (delegated hero (at dragon mountain) genie)
                           (at dragon mountain))
             :implies (at dragon mountain))
           (:axiom
             :context (and (delegated hero (at genie castle) genie)
                           (at genie castle))
             :implies (at genie castle))
           (:axiom
             :context (and (delegated hero (at genie mountain) genie)
                           (at genie mountain))
             :implies (at genie mountain))
           (:axiom
             :context (and (delegated hero (at hero castle) genie)
                           (at hero castle))
             :implies (at hero castle))
           (:axiom
             :context (and (delegated hero (at hero mountain) genie)
                           (at hero mountain))
             :implies (at hero mountain))
           (:axiom
             :context (and (delegated hero (at jasmine castle) genie)
                           (at jasmine castle))
             :implies (at jasmine castle))
           (:axiom
             :context (and (delegated hero (at jasmine mountain) genie)
                           (at jasmine mountain))
             :implies (at jasmine mountain))
           (:axiom
             :context (and (delegated hero (at king castle) genie)
                           (at king castle))
             :implies (at king castle))
           (:axiom
             :context (and (delegated hero (at king mountain) genie)
                           (at king mountain))
             :implies (at king mountain))
           (:axiom
             :context (and (delegated hero (in genie lamp) genie)
                           (in genie lamp))
             :implies (in genie lamp))
           (:axiom
             :context (and (delegated hero (has dragon lamp) genie)
                           (has dragon lamp))
             :implies (has dragon lamp))
           (:axiom
             :context (and (delegated hero (has genie lamp) genie)
                           (has genie lamp))
             :implies (has genie lamp))
           (:axiom
             :context (and (delegated hero (has hero lamp) genie)
                           (has hero lamp))
             :implies (has hero lamp))
           (:axiom
             :context (and (delegated hero (has jasmine lamp) genie)
                           (has jasmine lamp))
             :implies (has jasmine lamp))
           (:axiom
             :context (and (delegated hero (has king lamp) genie)
                           (has king lamp))
             :implies (has king lamp))
           (:axiom
             :context (and (delegated hero (loyal-to hero king) genie)
                           (loyal-to hero king))
             :implies (loyal-to hero king))
           (:axiom
             :context (and (delegated hero (controls hero genie) genie)
                           (controls hero genie))
             :implies (controls hero genie))
           (:axiom
             :context (and (delegated hero (controls jasmine genie) genie)
                           (controls jasmine genie))
             :implies (controls jasmine genie))
           (:axiom
             :context (and (delegated hero (controls king genie) genie)
                           (controls king genie))
             :implies (controls king genie))
           (:axiom
             :context (and (delegated hero (loves hero jasmine) genie)
                           (loves hero jasmine))
             :implies (loves hero jasmine))
           (:axiom
             :context (and (delegated hero (loves jasmine hero) genie)
                           (loves jasmine hero))
             :implies (loves jasmine hero))
           (:axiom
             :context (and (delegated hero (loves jasmine king) genie)
                           (loves jasmine king))
             :implies (loves jasmine king))
           (:axiom
             :context (and (delegated hero (loves king jasmine) genie)
                           (loves king jasmine))
             :implies (loves king jasmine))
           (:axiom
             :context (and (delegated hero (married-to hero jasmine) genie)
                           (married-to hero jasmine))
             :implies (married-to hero jasmine))
           (:axiom
             :context (and (delegated hero (married-to jasmine hero) genie)
                           (married-to jasmine hero))
             :implies (married-to jasmine hero))
           (:axiom
             :context (and (delegated hero (married-to jasmine king) genie)
                           (married-to jasmine king))
             :implies (married-to jasmine king))
           (:axiom
             :context (and (delegated hero (married-to king jasmine) genie)
                           (married-to king jasmine))
             :implies (married-to king jasmine))
           (:axiom
             :context (and (delegated king (alive dragon) hero)
                           (alive dragon))
             :implies (alive dragon))
           (:axiom
             :context (and (delegated king (alive dragon) genie)
                           (alive dragon))
             :implies (alive dragon))
           (:axiom
             :context (and (delegated king (alive genie) hero)
                           (alive genie))
             :implies (alive genie))
           (:axiom
             :context (and (delegated king (alive genie) genie)
                           (alive genie))
             :implies (alive genie))
           (:axiom
             :context (and (delegated king (alive hero) hero)
                           (alive hero))
             :implies (alive hero))
           (:axiom
             :context (and (delegated king (alive hero) genie)
                           (alive hero))
             :implies (alive hero))
           (:axiom
             :context (and (delegated king (alive jasmine) hero)
                           (alive jasmine))
             :implies (alive jasmine))
           (:axiom
             :context (and (delegated king (alive jasmine) genie)
                           (alive jasmine))
             :implies (alive jasmine))
           (:axiom
             :context (and (delegated king (alive king) hero)
                           (alive king))
             :implies (alive king))
           (:axiom
             :context (and (delegated king (alive king) genie)
                           (alive king))
             :implies (alive king))
           (:axiom
             :context (and (delegated king (at dragon castle) hero)
                           (at dragon castle))
             :implies (at dragon castle))
           (:axiom
             :context (and (delegated king (at dragon castle) genie)
                           (at dragon castle))
             :implies (at dragon castle))
           (:axiom
             :context (and (delegated king (at dragon mountain) hero)
                           (at dragon mountain))
             :implies (at dragon mountain))
           (:axiom
             :context (and (delegated king (at dragon mountain) genie)
                           (at dragon mountain))
             :implies (at dragon mountain))
           (:axiom
             :context (and (delegated king (at genie castle) hero)
                           (at genie castle))
             :implies (at genie castle))
           (:axiom
             :context (and (delegated king (at genie castle) genie)
                           (at genie castle))
             :implies (at genie castle))
           (:axiom
             :context (and (delegated king (at genie mountain) hero)
                           (at genie mountain))
             :implies (at genie mountain))
           (:axiom
             :context (and (delegated king (at genie mountain) genie)
                           (at genie mountain))
             :implies (at genie mountain))
           (:axiom
             :context (and (delegated king (at hero castle) hero)
                           (at hero castle))
             :implies (at hero castle))
           (:axiom
             :context (and (delegated king (at hero castle) genie)
                           (at hero castle))
             :implies (at hero castle))
           (:axiom
             :context (and (delegated king (at hero mountain) hero)
                           (at hero mountain))
             :implies (at hero mountain))
           (:axiom
             :context (and (delegated king (at hero mountain) genie)
                           (at hero mountain))
             :implies (at hero mountain))
           (:axiom
             :context (and (delegated king (at jasmine castle) hero)
                           (at jasmine castle))
             :implies (at jasmine castle))
           (:axiom
             :context (and (delegated king (at jasmine castle) genie)
                           (at jasmine castle))
             :implies (at jasmine castle))
           (:axiom
             :context (and (delegated king (at jasmine mountain) hero)
                           (at jasmine mountain))
             :implies (at jasmine mountain))
           (:axiom
             :context (and (delegated king (at jasmine mountain) genie)
                           (at jasmine mountain))
             :implies (at jasmine mountain))
           (:axiom
             :context (and (delegated king (at king castle) hero)
                           (at king castle))
             :implies (at king castle))
           (:axiom
             :context (and (delegated king (at king castle) genie)
                           (at king castle))
             :implies (at king castle))
           (:axiom
             :context (and (delegated king (at king mountain) hero)
                           (at king mountain))
             :implies (at king mountain))
           (:axiom
             :context (and (delegated king (at king mountain) genie)
                           (at king mountain))
             :implies (at king mountain))
           (:axiom
             :context (and (delegated king (in genie lamp) hero)
                           (in genie lamp))
             :implies (in genie lamp))
           (:axiom
             :context (and (delegated king (in genie lamp) genie)
                           (in genie lamp))
             :implies (in genie lamp))
           (:axiom
             :context (and (delegated king (has dragon lamp) hero)
                           (has dragon lamp))
             :implies (has dragon lamp))
           (:axiom
             :context (and (delegated king (has dragon lamp) genie)
                           (has dragon lamp))
             :implies (has dragon lamp))
           (:axiom
             :context (and (delegated king (has genie lamp) hero)
                           (has genie lamp))
             :implies (has genie lamp))
           (:axiom
             :context (and (delegated king (has genie lamp) genie)
                           (has genie lamp))
             :implies (has genie lamp))
           (:axiom
             :context (and (delegated king (has hero lamp) hero)
                           (has hero lamp))
             :implies (has hero lamp))
           (:axiom
             :context (and (delegated king (has hero lamp) genie)
                           (has hero lamp))
             :implies (has hero lamp))
           (:axiom
             :context (and (delegated king (has jasmine lamp) hero)
                           (has jasmine lamp))
             :implies (has jasmine lamp))
           (:axiom
             :context (and (delegated king (has jasmine lamp) genie)
                           (has jasmine lamp))
             :implies (has jasmine lamp))
           (:axiom
             :context (and (delegated king (has king lamp) hero)
                           (has king lamp))
             :implies (has king lamp))
           (:axiom
             :context (and (delegated king (has king lamp) genie)
                           (has king lamp))
             :implies (has king lamp))
           (:axiom
             :context (and (delegated king (loyal-to hero king) hero)
                           (loyal-to hero king))
             :implies (loyal-to hero king))
           (:axiom
             :context (and (delegated king (loyal-to hero king) genie)
                           (loyal-to hero king))
             :implies (loyal-to hero king))
           (:axiom
             :context (and (delegated king (controls hero genie) hero)
                           (controls hero genie))
             :implies (controls hero genie))
           (:axiom
             :context (and (delegated king (controls hero genie) genie)
                           (controls hero genie))
             :implies (controls hero genie))
           (:axiom
             :context (and (delegated king (controls jasmine genie) hero)
                           (controls jasmine genie))
             :implies (controls jasmine genie))
           (:axiom
             :context (and (delegated king (controls jasmine genie) genie)
                           (controls jasmine genie))
             :implies (controls jasmine genie))
           (:axiom
             :context (and (delegated king (controls king genie) hero)
                           (controls king genie))
             :implies (controls king genie))
           (:axiom
             :context (and (delegated king (controls king genie) genie)
                           (controls king genie))
             :implies (controls king genie))
           (:axiom
             :context (and (delegated king (loves hero jasmine) hero)
                           (loves hero jasmine))
             :implies (loves hero jasmine))
           (:axiom
             :context (and (delegated king (loves hero jasmine) genie)
                           (loves hero jasmine))
             :implies (loves hero jasmine))
           (:axiom
             :context (and (delegated king (loves jasmine hero) hero)
                           (loves jasmine hero))
             :implies (loves jasmine hero))
           (:axiom
             :context (and (delegated king (loves jasmine hero) genie)
                           (loves jasmine hero))
             :implies (loves jasmine hero))
           (:axiom
             :context (and (delegated king (loves jasmine king) hero)
                           (loves jasmine king))
             :implies (loves jasmine king))
           (:axiom
             :context (and (delegated king (loves jasmine king) genie)
                           (loves jasmine king))
             :implies (loves jasmine king))
           (:axiom
             :context (and (delegated king (loves king jasmine) hero)
                           (loves king jasmine))
             :implies (loves king jasmine))
           (:axiom
             :context (and (delegated king (loves king jasmine) genie)
                           (loves king jasmine))
             :implies (loves king jasmine))
           (:axiom
             :context (and (delegated king (married-to hero jasmine) hero)
                           (married-to hero jasmine))
             :implies (married-to hero jasmine))
           (:axiom
             :context (and (delegated king (married-to hero jasmine) genie)
                           (married-to hero jasmine))
             :implies (married-to hero jasmine))
           (:axiom
             :context (and (delegated king (married-to jasmine hero) hero)
                           (married-to jasmine hero))
             :implies (married-to jasmine hero))
           (:axiom
             :context (and (delegated king (married-to jasmine hero) genie)
                           (married-to jasmine hero))
             :implies (married-to jasmine hero))
           (:axiom
             :context (and (delegated king (married-to jasmine king) hero)
                           (married-to jasmine king))
             :implies (married-to jasmine king))
           (:axiom
             :context (and (delegated king (married-to jasmine king) genie)
                           (married-to jasmine king))
             :implies (married-to jasmine king))
           (:axiom
             :context (and (delegated king (married-to king jasmine) hero)
                           (married-to king jasmine))
             :implies (married-to king jasmine))
           (:axiom
             :context (and (delegated king (married-to king jasmine) genie)
                           (married-to king jasmine))
             :implies (married-to king jasmine))
           (:axiom
             :context (and (delegated jasmine (alive dragon) genie)
                           (alive dragon))
             :implies (alive dragon))
           (:axiom
             :context (and (delegated jasmine (alive genie) genie)
                           (alive genie))
             :implies (alive genie))
           (:axiom
             :context (and (delegated jasmine (alive hero) genie)
                           (alive hero))
             :implies (alive hero))
           (:axiom
             :context (and (delegated jasmine (alive jasmine) genie)
                           (alive jasmine))
             :implies (alive jasmine))
           (:axiom
             :context (and (delegated jasmine (alive king) genie)
                           (alive king))
             :implies (alive king))
           (:axiom
             :context (and (delegated jasmine (at dragon castle) genie)
                           (at dragon castle))
             :implies (at dragon castle))
           (:axiom
             :context (and (delegated jasmine (at dragon mountain) genie)
                           (at dragon mountain))
             :implies (at dragon mountain))
           (:axiom
             :context (and (delegated jasmine (at genie castle) genie)
                           (at genie castle))
             :implies (at genie castle))
           (:axiom
             :context (and (delegated jasmine (at genie mountain) genie)
                           (at genie mountain))
             :implies (at genie mountain))
           (:axiom
             :context (and (delegated jasmine (at hero castle) genie)
                           (at hero castle))
             :implies (at hero castle))
           (:axiom
             :context (and (delegated jasmine (at hero mountain) genie)
                           (at hero mountain))
             :implies (at hero mountain))
           (:axiom
             :context (and (delegated jasmine (at jasmine castle) genie)
                           (at jasmine castle))
             :implies (at jasmine castle))
           (:axiom
             :context (and (delegated jasmine (at jasmine mountain) genie)
                           (at jasmine mountain))
             :implies (at jasmine mountain))
           (:axiom
             :context (and (delegated jasmine (at king castle) genie)
                           (at king castle))
             :implies (at king castle))
           (:axiom
             :context (and (delegated jasmine (at king mountain) genie)
                           (at king mountain))
             :implies (at king mountain))
           (:axiom
             :context (and (delegated jasmine (in genie lamp) genie)
                           (in genie lamp))
             :implies (in genie lamp))
           (:axiom
             :context (and (delegated jasmine (has dragon lamp) genie)
                           (has dragon lamp))
             :implies (has dragon lamp))
           (:axiom
             :context (and (delegated jasmine (has genie lamp) genie)
                           (has genie lamp))
             :implies (has genie lamp))
           (:axiom
             :context (and (delegated jasmine (has hero lamp) genie)
                           (has hero lamp))
             :implies (has hero lamp))
           (:axiom
             :context (and (delegated jasmine (has jasmine lamp) genie)
                           (has jasmine lamp))
             :implies (has jasmine lamp))
           (:axiom
             :context (and (delegated jasmine (has king lamp) genie)
                           (has king lamp))
             :implies (has king lamp))
           (:axiom
             :context (and (delegated jasmine (loyal-to hero king) genie)
                           (loyal-to hero king))
             :implies (loyal-to hero king))
           (:axiom
             :context (and (delegated jasmine (controls hero genie) genie)
                           (controls hero genie))
             :implies (controls hero genie))
           (:axiom
             :context (and (delegated jasmine (controls jasmine genie) genie)
                           (controls jasmine genie))
             :implies (controls jasmine genie))
           (:axiom
             :context (and (delegated jasmine (controls king genie) genie)
                           (controls king genie))
             :implies (controls king genie))
           (:axiom
             :context (and (delegated jasmine (loves hero jasmine) genie)
                           (loves hero jasmine))
             :implies (loves hero jasmine))
           (:axiom
             :context (and (delegated jasmine (loves jasmine hero) genie)
                           (loves jasmine hero))
             :implies (loves jasmine hero))
           (:axiom
             :context (and (delegated jasmine (loves jasmine king) genie)
                           (loves jasmine king))
             :implies (loves jasmine king))
           (:axiom
             :context (and (delegated jasmine (loves king jasmine) genie)
                           (loves king jasmine))
             :implies (loves king jasmine))
           (:axiom
             :context (and (delegated jasmine (married-to hero jasmine) genie)
                           (married-to hero jasmine))
             :implies (married-to hero jasmine))
           (:axiom
             :context (and (delegated jasmine (married-to jasmine hero) genie)
                           (married-to jasmine hero))
             :implies (married-to jasmine hero))
           (:axiom
             :context (and (delegated jasmine (married-to jasmine king) genie)
                           (married-to jasmine king))
             :implies (married-to jasmine king))
           (:axiom
             :context (and (delegated jasmine (married-to king jasmine) genie)
                           (married-to king jasmine))
             :implies (married-to king jasmine))
           (:axiom
             :context (and (delegated dragon (alive dragon) genie)
                           (alive dragon))
             :implies (alive dragon))
           (:axiom
             :context (and (delegated dragon (alive genie) genie)
                           (alive genie))
             :implies (alive genie))
           (:axiom
             :context (and (delegated dragon (alive hero) genie)
                           (alive hero))
             :implies (alive hero))
           (:axiom
             :context (and (delegated dragon (alive jasmine) genie)
                           (alive jasmine))
             :implies (alive jasmine))
           (:axiom
             :context (and (delegated dragon (alive king) genie)
                           (alive king))
             :implies (alive king))
           (:axiom
             :context (and (delegated dragon (at dragon castle) genie)
                           (at dragon castle))
             :implies (at dragon castle))
           (:axiom
             :context (and (delegated dragon (at dragon mountain) genie)
                           (at dragon mountain))
             :implies (at dragon mountain))
           (:axiom
             :context (and (delegated dragon (at genie castle) genie)
                           (at genie castle))
             :implies (at genie castle))
           (:axiom
             :context (and (delegated dragon (at genie mountain) genie)
                           (at genie mountain))
             :implies (at genie mountain))
           (:axiom
             :context (and (delegated dragon (at hero castle) genie)
                           (at hero castle))
             :implies (at hero castle))
           (:axiom
             :context (and (delegated dragon (at hero mountain) genie)
                           (at hero mountain))
             :implies (at hero mountain))
           (:axiom
             :context (and (delegated dragon (at jasmine castle) genie)
                           (at jasmine castle))
             :implies (at jasmine castle))
           (:axiom
             :context (and (delegated dragon (at jasmine mountain) genie)
                           (at jasmine mountain))
             :implies (at jasmine mountain))
           (:axiom
             :context (and (delegated dragon (at king castle) genie)
                           (at king castle))
             :implies (at king castle))
           (:axiom
             :context (and (delegated dragon (at king mountain) genie)
                           (at king mountain))
             :implies (at king mountain))
           (:axiom
             :context (and (delegated dragon (in genie lamp) genie)
                           (in genie lamp))
             :implies (in genie lamp))
           (:axiom
             :context (and (delegated dragon (has dragon lamp) genie)
                           (has dragon lamp))
             :implies (has dragon lamp))
           (:axiom
             :context (and (delegated dragon (has genie lamp) genie)
                           (has genie lamp))
             :implies (has genie lamp))
           (:axiom
             :context (and (delegated dragon (has hero lamp) genie)
                           (has hero lamp))
             :implies (has hero lamp))
           (:axiom
             :context (and (delegated dragon (has jasmine lamp) genie)
                           (has jasmine lamp))
             :implies (has jasmine lamp))
           (:axiom
             :context (and (delegated dragon (has king lamp) genie)
                           (has king lamp))
             :implies (has king lamp))
           (:axiom
             :context (and (delegated dragon (loyal-to hero king) genie)
                           (loyal-to hero king))
             :implies (loyal-to hero king))
           (:axiom
             :context (and (delegated dragon (controls hero genie) genie)
                           (controls hero genie))
             :implies (controls hero genie))
           (:axiom
             :context (and (delegated dragon (controls jasmine genie) genie)
                           (controls jasmine genie))
             :implies (controls jasmine genie))
           (:axiom
             :context (and (delegated dragon (controls king genie) genie)
                           (controls king genie))
             :implies (controls king genie))
           (:axiom
             :context (and (delegated dragon (loves hero jasmine) genie)
                           (loves hero jasmine))
             :implies (loves hero jasmine))
           (:axiom
             :context (and (delegated dragon (loves jasmine hero) genie)
                           (loves jasmine hero))
             :implies (loves jasmine hero))
           (:axiom
             :context (and (delegated dragon (loves jasmine king) genie)
                           (loves jasmine king))
             :implies (loves jasmine king))
           (:axiom
             :context (and (delegated dragon (loves king jasmine) genie)
                           (loves king jasmine))
             :implies (loves king jasmine))
           (:axiom
             :context (and (delegated dragon (married-to hero jasmine) genie)
                           (married-to hero jasmine))
             :implies (married-to hero jasmine))
           (:axiom
             :context (and (delegated dragon (married-to jasmine hero) genie)
                           (married-to jasmine hero))
             :implies (married-to jasmine hero))
           (:axiom
             :context (and (delegated dragon (married-to jasmine king) genie)
                           (married-to jasmine king))
             :implies (married-to jasmine king))
           (:axiom
             :context (and (delegated dragon (married-to king jasmine) genie)
                           (married-to king jasmine))
             :implies (married-to king jasmine))))