(define (space get-ark)
  (:literals (alive army)
             (not (alive army))
             (alive indiana)
             (not (alive indiana))
             (alive nazis)
             (not (alive nazis))
             (armed army)
             (not (armed army))
             (armed indiana)
             (not (armed indiana))
             (armed nazis)
             (not (armed nazis))
             (at army tanis)
             (not (at army tanis))
             (at army usa)
             (not (at army usa))
             (at indiana tanis)
             (not (at indiana tanis))
             (at indiana usa)
             (not (at indiana usa))
             (at nazis tanis)
             (not (at nazis tanis))
             (at nazis usa)
             (not (at nazis usa))
             (burried ark tanis)
             (not (burried ark tanis))
             (has army ark)
             (not (has army ark))
             (has army gun)
             (not (has army gun))
             (has indiana ark)
             (not (has indiana ark))
             (has indiana gun)
             (not (has indiana gun))
             (has nazis ark)
             (not (has nazis ark))
             (has nazis gun)
             (not (has nazis gun))
             (intends army (alive army))
             (intends army (has army ark))
             (intends indiana (alive indiana))
             (intends indiana (has army ark))
             (intends nazis (alive nazis))
             (intends nazis (open ark))
             (knows-location indiana ark tanis)
             (open ark))
  (:steps (travel indiana usa tanis)
          (travel indiana tanis usa)
          (travel nazis usa tanis)
          (travel nazis tanis usa)
          (travel army usa tanis)
          (travel army tanis usa)
          (excavate indiana ark tanis)
          (give indiana ark nazis usa)
          (give indiana ark nazis tanis)
          (give indiana ark army usa)
          (give indiana ark army tanis)
          (give indiana gun nazis usa)
          (give indiana gun nazis tanis)
          (give indiana gun army usa)
          (give indiana gun army tanis)
          (give nazis ark indiana usa)
          (give nazis ark indiana tanis)
          (give nazis ark army usa)
          (give nazis ark army tanis)
          (give nazis gun indiana usa)
          (give nazis gun indiana tanis)
          (give nazis gun army usa)
          (give nazis gun army tanis)
          (give army ark indiana usa)
          (give army ark indiana tanis)
          (give army ark nazis usa)
          (give army ark nazis tanis)
          (give army gun indiana usa)
          (give army gun indiana tanis)
          (give army gun nazis usa)
          (give army gun nazis tanis)
          (kill indiana gun nazis usa)
          (kill indiana gun nazis tanis)
          (kill indiana gun army usa)
          (kill indiana gun army tanis)
          (kill nazis gun indiana usa)
          (kill nazis gun indiana tanis)
          (kill nazis gun army usa)
          (kill nazis gun army tanis)
          (kill army gun indiana usa)
          (kill army gun indiana tanis)
          (kill army gun nazis usa)
          (kill army gun nazis tanis)
          (take indiana ark nazis usa)
          (take indiana ark nazis tanis)
          (take indiana ark army usa)
          (take indiana ark army tanis)
          (take indiana gun nazis usa)
          (take indiana gun nazis tanis)
          (take indiana gun army usa)
          (take indiana gun army tanis)
          (take nazis ark indiana usa)
          (take nazis ark indiana tanis)
          (take nazis ark army usa)
          (take nazis ark army tanis)
          (take nazis gun indiana usa)
          (take nazis gun indiana tanis)
          (take nazis gun army usa)
          (take nazis gun army tanis)
          (take army ark indiana usa)
          (take army ark indiana tanis)
          (take army ark nazis usa)
          (take army ark nazis tanis)
          (take army gun indiana usa)
          (take army gun indiana tanis)
          (take army gun nazis usa)
          (take army gun nazis tanis)
          (open-ark nazis))
  (:axioms (:axiom
             :context (and (not (armed indiana))
                           (has indiana gun))
             :implies (armed indiana))
           (:axiom
             :context (and (not (armed nazis))
                           (has nazis gun))
             :implies (armed nazis))
           (:axiom
             :context (and (not (armed army))
                           (has army gun))
             :implies (armed army))
           (:axiom
             :context (and (armed indiana)
                           (not (has indiana gun)))
             :implies (not (armed indiana)))
           (:axiom
             :context (and (armed nazis)
                           (not (has nazis gun)))
             :implies (not (armed nazis)))
           (:axiom
             :context (and (armed army)
                           (not (has army gun)))
             :implies (not (armed army)))))