(define (plan win-solution)
  (:problem win)
  (:steps (walk goblin tower crossroads)
          (walk goblin crossroads bridge)
          (walk goblin bridge junction)
          (walk goblin junction town)
          (walk goblin town shop)
          (pickup goblin tonic shop)
          (pickup goblin teleport_spell_1 shop)
          (cast_teleport_spell goblin teleport_spell_1 shop bridge)
          (walk goblin bridge crossroads)
          (walk goblin crossroads tower)))