(define (plan win-solution)
  (:problem win)
  (:steps (walk goblin tower crossroads)
          (walk goblin crossroads bridge)
          (walk goblin bridge junction)
          (walk goblin junction town)
          (walk goblin town shop)
          (pickup goblin tonic shop)
          (attack chemist goblin shop)
          (non-executed (pickup goblin teleport_spell_1 shop))
          (non-executed (cast_teleport_spell goblin teleport_spell_1 shop bridge))
          (non-executed (walk goblin bridge crossroads))
          (non-executed (walk goblin crossroads tower))))