(define (space marriage)
  (:literals (alive gargax)
             (not (alive gargax))
             (alive rory)
             (not (alive rory))
             (alive talia)
             (not (alive talia))
             (alive vince)
             (not (alive vince))
             (at gargax cave)
             (not (at gargax cave))
             (at gargax village)
             (not (at gargax village))
             (at rory cave)
             (not (at rory cave))
             (at rory village)
             (not (at rory village))
             (at talia cave)
             (not (at talia cave))
             (at talia village)
             (not (at talia village))
             (at treasure cave)
             (at vince cave)
             (not (at vince cave))
             (at vince village)
             (not (at vince village))
             (belongsto treasure gargax)
             (not (happy gargax))
             (happy rory)
             (not (happy rory))
             (happy talia)
             (not (happy talia))
             (happy vince)
             (not (happy vince))
             (not (has gargax money))
             (not (has gargax treasure))
             (has rory treasure)
             (has talia treasure)
             (has vince money)
             (has vince treasure)
             (hasaccepted rory talia)
             (hasaccepted talia rory)
             (hasaccepted talia vince)
             (hasproposed rory talia)
             (hasproposed talia rory)
             (hasproposed vince talia)
             (hungry gargax)
             (not (hungry gargax))
             (intends gargax (alive gargax))
             (intends gargax (has gargax treasure))
             (intends gargax (not (hungry gargax)))
             (intends gargax (rich gargax))
             (intends rory (alive rory))
             (intends rory (happy rory))
             (intends talia (alive talia))
             (intends talia (happy talia))
             (intends talia (rich talia))
             (intends vince (alive vince))
             (intends vince (happy vince))
             (intends vince (rich vince))
             (loves rory talia)
             (loves talia rory)
             (loves vince talia)
             (marriedto rory talia)
             (marriedto talia rory)
             (marriedto talia vince)
             (marriedto vince talia)
             (rich gargax)
             (not (rich gargax))
             (rich rory)
             (not (rich rory))
             (rich talia)
             (not (rich talia))
             (rich vince)
             (not (rich vince))
             (single rory)
             (not (single rory))
             (single talia)
             (not (single talia))
             (single vince)
             (not (single vince)))
  (:steps (travel talia village village)
          (travel talia village cave)
          (travel talia cave village)
          (travel talia cave cave)
          (travel rory village village)
          (travel rory village cave)
          (travel rory cave village)
          (travel rory cave cave)
          (travel vince village village)
          (travel vince village cave)
          (travel vince cave village)
          (travel vince cave cave)
          (travel gargax village village)
          (travel gargax village cave)
          (travel gargax cave village)
          (travel gargax cave cave)
          (propose talia rory village)
          (propose talia rory cave)
          (propose rory talia village)
          (propose rory talia cave)
          (propose vince talia village)
          (propose vince talia cave)
          (accept talia rory village)
          (accept talia rory cave)
          (accept talia vince village)
          (accept talia vince cave)
          (accept rory talia village)
          (accept rory talia cave)
          (marry talia rory village)
          (marry talia rory cave)
          (marry rory talia village)
          (marry rory talia cave)
          (marry vince talia village)
          (marry vince talia cave)
          (steal talia gargax treasure cave)
          (steal rory gargax treasure cave)
          (steal vince gargax treasure cave)
          (get-hungry gargax)
          (eat gargax talia village)
          (eat gargax talia cave)
          (eat gargax rory village)
          (eat gargax rory cave)
          (eat gargax vince village)
          (eat gargax vince cave)
          (eat gargax gargax village)
          (eat gargax gargax cave))
  (:axioms))