(define (plan do-heist-solution)
  (:problem do-heist)
  (:steps (hatch-plan robbie six-shooter brown-horse bank mother-lode)
          (open jill general-store)
          (move-once sally main-street bank)
          (withdraw-money sally bank dress-money)
          (move-once sally bank main-street)
          (sell sally anne tomatoes tomato-money main-street)
          (move-once robbie main-street dark-alley)
          (hide-in-dark-alley robbie dark-alley)
          (move-once barney barneys-room saloon)
          (pickpocket robbie sally dress-money main-street dark-alley)
          (move-once robbie dark-alley main-street)
          (move-once robbie main-street saloon)
          (buy-drinks-for robbie barney dress-money saloon)
          (escort-drunk-friend robbie barney saloon main-street)
          (escort-drunk-friend robbie barney main-street dark-alley)
          (lay-to-rest-in-alley robbie barney dark-alley bank)
          (take-thing-off-sleeper robbie barney six-shooter dark-alley)
          (move-once robbie dark-alley main-street)
          (move-once robbie main-street saloon)
          (cheat-at-poker robbie poker-game dress-money poker-money saloon)
          (move-once robbie saloon main-street)
          (pawn-valuable robbie pawn-broker locket main-street locket-money)
          (buy-valuable robbie horse-seller brown-horse main-street locket-money)
          (ride-horse-to robbie brown-horse main-street bank)
          (hold-up-bank robbie six-shooter bank tom)
          (collect-money-from-heist robbie bank mother-lode)
          (getaway-with-money robbie mother-lode brown-horse bank out-of-town)
          (pick-up tom handcuffs sheriffs-office)
          (move-once tom sheriffs-office barber-shop)
          (ride-horse-to tom white-horse barber-shop out-of-town)
          (arrest robbie tom out-of-town handcuffs mother-lode)))
