(define (space explore)
  (:literals (alive lizard)
             (not (alive lizard))
             (alive zoe)
             (not (alive zoe))
             (at lizard cave)
             (at zoe cave)
             (not (at zoe cave))
             (at zoe ship)
             (not (at zoe ship))
             (at zoe surface)
             (not (at zoe surface))
             (captain zoe ship)
             (fighting lizard lizard)
             (not (fighting lizard lizard))
             (fighting lizard zoe)
             (not (fighting lizard zoe))
             (fighting zoe lizard)
             (not (fighting zoe lizard))
             (fighting zoe zoe)
             (not (fighting zoe zoe))
             (friends lizard zoe)
             (friends zoe lizard)
             (guardian lizard surface)
             (habitable cave)
             (habitable ship)
             (habitable surface)
             (intends lizard (alive lizard))
             (intends lizard (not (alive zoe)))
             (intends lizard (not (fighting lizard lizard)))
             (intends lizard (not (fighting zoe lizard)))
             (intends lizard (safe lizard))
             (intends zoe (alive zoe))
             (intends zoe (friends zoe lizard))
             (intends zoe (not (fighting lizard zoe)))
             (intends zoe (not (fighting zoe zoe)))
             (intends zoe (safe zoe))
             (safe cave)
             (safe lizard)
             (safe ship)
             (safe surface)
             (safe zoe)
             (not (safe zoe))
             (stunned lizard)
             (not (stunned lizard))
             (stunned zoe)
             (not (stunned zoe)))
  (:steps (teleport-from-ship zoe ship cave)
          (teleport-from-ship zoe ship surface)
          (teleport-to-ship zoe cave ship)
          (teleport-to-ship zoe surface ship)
          (attack zoe zoe ship)
          (attack zoe zoe cave)
          (attack zoe zoe surface)
          (attack zoe lizard cave)
          (attack lizard zoe cave)
          (attack lizard lizard cave)
          (kill zoe zoe)
          (kill zoe lizard)
          (kill lizard zoe)
          (kill lizard lizard)
          (stun zoe zoe)
          (stun zoe lizard)
          (stun lizard zoe)
          (stun lizard lizard)
          (break-free zoe)
          (break-free lizard)
          (make-peace zoe lizard cave)
          (begin-erupt surface)
          (erupt surface))
  (:axioms))