;;;
;;; Python generated problem description for a narrative based on Talk of the Town
;;;
(define (problem tot)
  (:domain tot-domain)
  (:objects Patricia_Hense James_Penninger Richard_Skaar Gary_Fairless Jacqueline_Knepper - character
)
  (:init (at Patricia_Hense Dawnbreak-Airport)
	 (love_interest Patricia_Hense Gary_Fairless)
	 (introvert Patricia_Hense)
	 (likes Patricia_Hense Gary_Fairless)
	 (dislikes Patricia_Hense Richard_Skaar)
	 (at James_Penninger Starlight-Park)
	 (introvert James_Penninger)
	 (at Richard_Skaar Dawnbreak-Airport)
	 (extrovert Richard_Skaar)
	 (likes Richard_Skaar Gary_Fairless)
	 (at Gary_Fairless Dawnbreak-Airport)
	 (introvert Gary_Fairless)
	 (worst_enemy Gary_Fairless Richard_Skaar)
	 (likes Gary_Fairless Patricia_Hense)
	 (dislikes Gary_Fairless Richard_Skaar)
	 (at Jacqueline_Knepper Hip-Hop-Dance-Studio)
	 (introvert Jacqueline_Knepper)
	 (item_at flower Starlight-Park)
	 (item_at panini Sunset-Bistro)
	 (item_at overpriced_food Dawnbreak-Airport)
	 (item_at sick_dance_moves_brochure Hip-Hop-Dance-Studio)
	 (intends Patricia_Hense (loves Gary_Fairless Patricia_Hense))
	 (intends Richard_Skaar (likes Patricia_Hense Richard_Skaar))
	 (intends Richard_Skaar (dislikes Patricia_Hense Gary_Fairless))
	 (intends Richard_Skaar (persuadedtodislike Richard_Skaar))
	 (intends Richard_Skaar (likes Gary_Fairless Richard_Skaar)))
  (:goal (and (loves Gary_Fairless Patricia_Hense)
	      (likes Patricia_Hense Richard_Skaar)
	      (persuadedtodislike Richard_Skaar))))
